version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: frappe
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:9000
    volumes:
      - .:/my_diary
    ports:
      - "9000:9000"
    depends_on:
      - db