# Generated by Django 3.2.9 on 2021-11-04 20:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date_created', models.DateTimeField(default=datetime.datetime(2021, 11, 4, 20, 57, 54, 502134, tzinfo=utc))),
            ],
            options={
                'verbose_name_plural': 'Entries',
            },
        ),
    ]
